### ISSUE TITLE
Binder ne dela

### ISSUE THREAD

**Issue by mitja-mandic** [mitja-mandic/APPR-2019-20#2]
Poskusno sem pognal moj projekt v binderju in dobil obvestilo, da se je zgodila napaka in ne razumem zakaj. Nobenega posebnega obestila ni bilo zraven..
Mitja

**Comment by jaanos** [comment]
Če želiš videti, kaj gre narobe pri poganjanju v Binderju, lahko poženeš RStudio v Binderju (ali pa v URL-ju Binderja vse od `shiny` naprej nadomestiš z `rstudio`, da se slika ne nalaga še enkrat) in poskusiš tam pognati poročilo.

Sicer pa ti poročilo ne deluje v Binderju, ker pripravljena slika nima nameščene knjižnice `useful` - za to bom še poskrbel. Poleg tega v poročilu kličeš program `uvoz_podatkov.r`, medtem ko ima datoteka v mapi `uvoz` končnico `.R` (velika črka!) - to poenoti, da bo delovalo na vseh sistemih.

Prav tako se pojavi še problem pri branju razpredelnice `populacija`. Če se na začetku pojavi kak čuden znak (kot se je pri tebi v imenu prvega stolpca), potem je to najverjetneje BOM - oznaka, ki določa, kateri različici standarda Unicode je uporabljena. V veliki večini primerov se uporablja kodiranje **UTF-8**, ki ga je potrebno podati pri uvažanju (poleg tega svetujem, da namesto `read.csv` uporabiš funkcijo `read_csv` iz knjižnice `readr` - slednja presledkov in ostalih posebnih znakov v imenih stolpcev ne zamenja s piko):
```R
populacija <- read_csv("podatki/populacija.csv", na="..", locale=locale(encoding="UTF-8")) %>%
  select(-"Series Name", -"Series Code", -"Country Code")
```

Po zgornjih popravkih se mi poročilo prevede, grafi v aplikaciji Shiny pa (še) ne delujejo.

**Comment by mitja-mandic** [comment]
Pozdravljeni,
popravil sem, kar ste napisali, vendar se je pojavil nov problem pri vizualizaciji:
`zemljevid_median <- tm_shape(merge(svet, median_age2018, by.x = "NAME", by.y = "country")) + 
  tm_polygons(col = "median", midpoint = 1, legend.hist = TRUE, palette = "Pastel2") +
  tm_layout(legend.outside = TRUE) `
Ko to poženem, dobim napako *Error in .local(x, y, ...) : non-unique matches detected*
(prej teh napak nikoli nisem dobival, vse je delovalo normalno).
V spletni verziji RStudia pa se mi poročilo še vedno ne prevede.

**Comment by jaanos** [comment]
Problem se pojavi, ker je Palestina (pod imenom *Palestinian Territory*) dvakrat v seznamu (z različnimi podatki). Vpogled v zgodovino na Wikipediji razkrije, da se prvi podatek (225. mesto) nanaša na Gazo, drugi (186. mesto) pa na Zahodni breg. Svetujem, da eno od pojavitev izbrišeš - potem bi moralo delovati.

**Comment by mitja-mandic** [comment]
Hvala, sem popravil in sedaj vse funkcionira kot mora.
