### ISSUE TITLE
Zaključek

### ISSUE THREAD

**Issue by mitja-mandic** [mitja-mandic/APPR-2019-20#3]
Projekt sem končal, se vam zdi še kaj potrebno popraviti?

**Comment by jaanos** [comment]
Poročilo deluje, tako da bom dodal povezavo na repozitorij za zagovore. Če se še nisi, se lahko z @alenFMF domeniš za termin zagovora. Če boš do takrat še kaj spreminjal, prosim javi, da posodobim povezavo.

Imam samo dve pripombi bolj estetske narave. Pri grafu spreminjanja starostne sestave pri `aes` namesto `color` raje uporabi parameter `fill`, da se stolpci pobarvajo (in ne samo obrobijo). Pri grafu BDP in medianske starosti pa bi morda bilo vendarle zanimivo, če bi z barvami predstavil kako dejansko spremenljivko - glede na tvojo temo bi bila očitna izbira večinska religija, lahko pa tudi kaj drugega, npr. celina.

**Comment by mitja-mandic** [comment]
Sem popravil, prosim osvežite povezavo. Hvala za vso pomoč.

**Comment by jaanos** [comment]
V redu, sem posodobil povezavo.
